config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'

  devise_for :users, controllers: {sessions: 'sessions'}

  get '/home', to: 'visitors#home', as: 'home'
  get '/mysol', to: 'visitors#mysol', as: 'mysol'
  get '/destination', to: 'visitors#destination', as: 'destination'
  get '/solblog', to: 'visitors#solblog', as: 'solblog'
  get '/travel', to: 'visitors#travel', as: 'travel'

  resources :blogs
  resources :locations

  post '/photos/create', to: 'blogs#create_photo', as: 'photos'
  delete '/photos/:id', to: 'blogs#destroy_photo', as: 'photo'
  put '/destination/select_top', to: 'blogs#select_top', as: 'select_top'
  post '/support', to: 'visitors#support', as: 'support'

end

app/models/blog.rb
class Blog < ActiveRecord::Base

	BLOG_MAIN = 'Main'
	BLOG_MYSOL = 'MySol'
	BLOG_EAT = 'EatBlog'
	BLOG_PLAY = 'PlayBlog'
	BLOG_STAY = 'StayBlog'

	BLOG_TYPES = [nil, BLOG_MAIN, BLOG_MYSOL, BLOG_EAT, BLOG_PLAY, BLOG_STAY]

	has_many :photos, dependent: :destroy
	belongs_to :location

	has_attached_file :picture, 
										:styles => { 
												:medium => "300x300>", 
												:thumb => "100x100>" 
										}, 
										:default_url => "/images/:style_missing.png"

	validates_presence_of :title, :body
	validates :blog_type, inclusion: { in: BLOG_TYPES}
	validates :category, inclusion: { in: [nil, true, false]}
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  default_scope { order('created_at DESC') }

  # category true => location landing page blog
  # category false => location sub page blogs
  scope :eat, -> { where(blog_type: BLOG_EAT, category: false) }
  scope :stay, -> { where(blog_type: BLOG_STAY, category: false) }
  scope :play, -> { where(blog_type: BLOG_PLAY, category: false) }
  scope :destination, -> { where(category: true) }
  scope :featured, -> { where(featured: true) }

  def self.main_blogs
  	where(blog_type: BLOG_MAIN)
  end

  def self.latest_blog
  	where('blog_type = ? ', BLOG_MAIN).first
  end

  def self.my_sol_blogs
  	where(blog_type: BLOG_MYSOL)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_filter :authenticate_user!

	before_filter :get_type
	before_filter :get_locations

	def index
		if @name.blank?
			if @type == Blog::BLOG_MAIN
				@blogs = Blog.main_blogs
			elsif @type == Blog::BLOG_MYSOL
				@blogs = Blog.my_sol_blogs
			end
		else
			@location = Location.find_by_name @name
			@destination = @location.blogs.destination
		end
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = Blog.new permit_blog_params
		@blog.blog_type = @type
		@blog.location = Location.find_by_name(@name)
		@blog.category = @category
		if @blog.save!
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "#{@type} Blog is successfully created."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), alert: "Failed to create #{@type} Blog."
		end
	end

	def edit
		@blog = Blog.find params[:id]
	end

	def select_top
		@location = Location.find_by_name params[:name]
		@location.sub_blogs.update_all featured: false
		@blogs = Blog.where(id: params[:featured])

		if @blogs.update_all featured: true
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Selecting top blogs is successfully finished."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Failed to select top blogs."
		end
	end

	def update
		@blog = Blog.find params[:id]

		if @blog.update_attributes permit_blog_params
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "#{@type} Blog is successfully updated."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), alert: "Failed to update #{@type} Blog."
		end
	end

	def destroy
		@blog = Blog.find params[:id]

		if @blog.destroy
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "#{@type} Blog is successfully destroyed."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), alert: "Failed to destroy #{@type} Blog."
		end
	end

	def show
		@blog = Blog.find params[:id]
	end

	def create_photo
		@photo = Photo.new permit_photo_params
		if @photo.save
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Photo is successfully created."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Failed to create photo."
		end
	end

	def destroy_photo
		@photo = Photo.find(params[:id])

		if @photo.destroy
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Photo is successfully destroyed."
		else
			redirect_to blogs_path(type: @type, name: @name, category: @category), notice: "Failed to destroy photo."
		end
	end

	def locations
		
	end

	private

	def get_type
		@type = params[:type]
		@name = params[:name]
		@category = params[:category]
	end

	def permit_blog_params
		params.require(:blog).permit(:title, :body, :picture, :link_url)
	end

	def permit_photo_params
		params.require(:photo).permit(:title, :url, :location_id, :picture, :landing)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.haml
= form_for @blog, role: "form", url: (@blog.new_record? ? blogs_path(type: @type, name: @name, category: @category) : blog_path(type: @type, name: @name, category: @category)), method: (@blog.new_record? ? :post : :put) do |f|

	%div
		%table{:align=>'center'}
			%tr
				%td{:width=>'50px'}
					= f.label :title, :class=>'control-label'
				%td{:width=>'300px'}
					= f.text_field :title, :class=>'form-control', :size=>80, :placeholder=>"Title here"
			%tr
				%td
					= f.label :link_url, :class=>'control-label'
				%td
					= f.text_field :link_url, :class=>'form-control', :size=>80, :placeholder=>"Link Url here"
			%tr
				%td
					= f.label :body, :class=>'control-label'
				%td
					= f.text_area :body, :class=>'form-control', :size=>80, :rows=>20, :placeholder=>"Content here"
			%tr
				%td
					= f.label :picture, :class=>'control-label'
				%td
					= f.file_field :picture
			%tr
				%td{:colspan=>2, :align=>'center', :height=>60}
					= f.submit :submit, :class=>'btn, btn-default'
	%br
	%br
	%br

app/views/blogs/edit.html.haml
.main
	%div{:text_agign=>'center'}
		= link_to "Back", blogs_path(type: @type, name: @name)

	%div
		= render 'form'

app/views/blogs/index.html.haml
.main
	.row
		.col-sm-12
			= render 'layouts/messages'
			- if @name.nil?
				%div
					- if @type == Blog::BLOG_MYSOL && @blogs.count != 0
						= link_to 'Edit MySol', edit_blog_path(@blogs.first, type: Blog::BLOG_MYSOL), class: "pull-left btn btn-success"
					- else
						= link_to 'Add new blog', new_blog_path(type: @type), class: "pull-left btn btn-success"
				%div
					%table#blog_edit_table.table{:align=> 'center'}
						%thead
							%td{:width=>'15%'} Title
							%td{:width=>'28%'} Body
							%td{:width=>'15%'} Picture
							%td{:width=>'15%'} Created At
							%td{:width=>'20%'} Actions
						%tbody
							- if !@blogs.nil? && @blogs.length > 0
								- @blogs.each do |blog|
									%tr
										%td= blog.title
										%td= raw blog.body[0..100]
										%td= image_tag blog.picture.url(:thumb)
										%td= blog.created_at.strftime "%D"
										%td
											= link_to 'Edit', edit_blog_path(blog, type: @type), class: "btn btn-primary btn-xs"
											- if @type == Blog::BLOG_MYSOL
												= link_to 'Show', mysol_path, class: "btn btn-primary btn-xs"
											- else
												= link_to 'Show', blog_path(blog, type: @type), class: "btn btn-primary btn-xs"
											- unless @type == Blog::BLOG_MYSOL
												= link_to 'Delete', blog_path(blog, type: Blog::BLOG_MAIN), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
							- else
								%tr
									%td{colspan: 5}
										%h3
											There's no blogs yet. Add 
											= link_to 'new blog', new_blog_path(type: @type)
											here.
			- else
				%h2 Main Blogs
				%div
					= link_to 'Add New Blog', new_blog_path(type: @type, name: @name, category: true), class: "pull-left btn btn-success"
				%table#blog_edit_table.table{:align=> 'center'}
					%thead
						%td{:width=>'15%'} Title
						%td{:width=>'28%'} Body
						%td{:width=>'15%'} Picture
						%td{:width=>'15%'} Created At
						%td{:width=>'20%'} Actions
					%tbody
						- if @destination.length > 0
							- @destination.each do |blog|
								%tr
									%td= blog.title
									%td= raw blog.body[0..100]
									%td= image_tag blog.picture.url(:thumb)
									%td= blog.created_at.strftime "%D"
									%td
										= link_to 'Edit', edit_blog_path(blog, type: @type, name: @name, category: true), class: "btn btn-primary btn-xs"
										= link_to 'Show', destination_path(name: @name), class: "btn btn-primary btn-xs"
										= link_to 'Delete', blog_path(blog, type: @type, name: @name, category: true), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
						- else
							%tr
								%td{colspan: 5}
									%h3
										There's no blogs yet. Add 
										= link_to 'new blog', new_blog_path(type: @type, name: @name, category: true)
										here.
				
				%br
				%br
				%h2 Select Top Rated Blogs
				%br
				= form_tag select_top_path(type: @type, name: @name, category: true), method: :put do
					= submit_tag "Save", class: "pull-left btn btn-success"
					%table#blog_edit_table.table{:align=> 'center'}
						%thead
							%td{:width=>'5%'} Top
							%td{:width=>'15%'} Title
							%td{:width=>'35%'} Body
							%td{:width=>'15%'} Type
							%td{:width=>'25%'} Created At
						%tbody
							- if @location.sub_blogs.length > 0
								- @location.sub_blogs.each do |blog|
									%tr
										%td= check_box_tag "featured[]", blog.id, blog.featured
										%td= blog.title
										%td= raw blog.body[0..100]
										%td= blog.blog_type
										%td= blog.created_at.strftime "%D"
				
				%br
				%br	
				%h2 Blogs for Eat
				%br
				%div
					= link_to 'Add New Blog', new_blog_path(type: Blog::BLOG_EAT, name: @name, category: false), class: "btn btn-success pull-left"
				%table#blog_edit_table.table{:align=> 'center'}
					%thead
						%td{:width=>'10%'} Title
						%td{:width=>'28%'} Body
						%td{:width=>'15%'} Picture
						%td{:width=>'15%'} Linked URL
						%td{:width=>'15%'} Created At
						%td{:width=>'15%'} Actions
					%tbody
						- if @location.blogs.eat.length > 0
							- @location.blogs.eat.each do |blog|
								%tr
									%td= blog.title
									%td= raw blog.body[0..100]
									%td= image_tag blog.picture.url(:thumb)
									%td= blog.link_url
									%td= blog.created_at.strftime "%D"
									%td
										= link_to 'Edit', edit_blog_path(blog, type: Blog::BLOG_EAT, name: @name, category: false), class: "btn btn-primary btn-xs"
										= link_to 'Show', destination_path(name: @name), class: "btn btn-primary btn-xs"
										= link_to 'Delete', blog_path(blog, type: Blog::BLOG_EAT, name: @name, category: @category), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
						- else
							%tr
								%td{colspan: 5}
									%h3
										There's no blogs yet. Add 
										= link_to 'new blog', new_blog_path(type: Blog::BLOG_EAT, name: @name, category: false)
										here.

				%br
				%br
				%h2 Blogs for Stay
				%div
					= link_to 'Add New Blog', new_blog_path(type: Blog::BLOG_STAY, name: @name, category: false), class: "btn btn-success pull-left"
				%table#blog_edit_table.table{:align=> 'center'}
					%thead
						%td{:width=>'10%'} Title
						%td{:width=>'28%'} Body
						%td{:width=>'15%'} Picture
						%td{:width=>'15%'} Linked URL
						%td{:width=>'15%'} Created At
						%td{:width=>'15%'} Actions
					%tbody
						- if @location.blogs.stay.length > 0
							- @location.blogs.stay.each do |blog|
								%tr
									%td= blog.title
									%td= raw blog.body[0..100]
									%td= image_tag blog.picture.url(:thumb)
									%td= blog.link_url
									%td= blog.created_at.strftime "%D"
									%td
										= link_to 'Edit', edit_blog_path(blog, type: Blog::BLOG_STAY, name: @name, category: false), class: "btn btn-primary btn-xs"
										= link_to 'Show', destination_path(name: @name), class: "btn btn-primary btn-xs"
										= link_to 'Delete', blog_path(blog, type: Blog::BLOG_STAY, name: @name, category: @category), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
						- else
							%tr
								%td{colspan: 5}
									%h3
										There's no blogs yet. Add 
										= link_to 'new blog', new_blog_path(type: Blog::BLOG_STAY, name: @name, category: false)
										here.

				%br
				%br
				%h2 Blogs for Play
				%div
					= link_to 'Add New Blog', new_blog_path(type: Blog::BLOG_PLAY, name: @name, category: false), class: "btn btn-success pull-left"
				%table#blog_edit_table.table{:align=> 'center'}
					%thead
						%td{:width=>'10%'} Title
						%td{:width=>'28%'} Body
						%td{:width=>'15%'} Picture
						%td{:width=>'15%'} Linked URL
						%td{:width=>'15%'} Created At
						%td{:width=>'15%'} Actions
					%tbody
						- if @location.blogs.play.length > 0
							- @location.blogs.play.each do |blog|
								%tr
									%td= blog.title
									%td= raw blog.body[0..100]
									%td= image_tag blog.picture.url(:thumb)
									%td= blog.link_url
									%td= blog.created_at.strftime "%D"
									%td
										= link_to 'Edit', edit_blog_path(blog, type: Blog::BLOG_PLAY, name: @name, category: false), class: "btn btn-primary btn-xs"
										= link_to 'Show', destination_path(name: @name), class: "btn btn-primary btn-xs"
										= link_to 'Delete', blog_path(blog, type: Blog::BLOG_PLAY, name: @name, category: @category), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
						- else
							%tr
								%td{colspan: 5}
									%h3
										There's no blogs yet. Add 
										= link_to 'new blog', new_blog_path(type: Blog::BLOG_PLAY, name: @name, category: false)
										here.

				%br
				%br
				%h2 Photos
				%br
				.row
					- @location.all_photos.each do |p|
						.col-md-3.col-sm-4.col-xs.6{:style=>"height:150px;"}
							%div
								= image_tag p.picture.url(:thumb), :class=>'img-thumbnail'
							%div{:style=>"position:absolute;bottom:10px"}
								= link_to 'Delete', photo_path(p, name: @name, category: false), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"

				= form_for :photo, url: photos_path(name: @name, category: false), method: :post, multipart: true do |f|
					%table{:align=>'center'}
						%tr
							%td{:width=>'50', :align=>'right'}
								= f.label :title, :class=>'control-label'
							%td
								= f.text_field :title, :class=>'form-control', :size=>100, :placeholder=>"Title here"
							%td{:width=>'50', :align=>'right'}
								= f.label "URL", :class=>'control-label'
							%td
								= f.text_field :url, :class=>'form-control', :size=>150, :placeholder=>"URL here"
							%td{:width=>'80', :align=>'right'}
								= f.label :picture, :class=>'control-label'
							%td
								= f.file_field :picture
						%tr
							%td{:colspan=>6, :align=>'center', :height=>60}
								= f.submit "Save", :class=>'btn, btn-default'

					= f.hidden_field :location_id, value: @location.id
					= f.hidden_field :landing, value: false
				%br
				%br

app/views/blogs/new.html.haml
.main
	%div
		= link_to "Back", blogs_path(type: @type, name: @name)

	%div
		= render 'form'

app/views/blogs/show.html.haml
%div.main
	%div.blog_section
		%pre
			= link_to "Back", blogs_path(type: @type)
		%div= image_tag @blog.picture.url, class: "blog_big_img"
		%div.blog_title
			= @blog.created_at.strftime "%D" + "  -  " + @blog.title
		%div.blog_content= raw @blog.body