config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'

  devise_for :users, controllers: {sessions: 'sessions'}

  get '/home', to: 'visitors#home', as: 'home'
  get '/mysol', to: 'visitors#mysol', as: 'mysol'
  get '/destination', to: 'visitors#destination', as: 'destination'
  get '/solblog', to: 'visitors#solblog', as: 'solblog'
  get '/travel', to: 'visitors#travel', as: 'travel'

  resources :blogs
  resources :locations

  post '/photos/create', to: 'blogs#create_photo', as: 'photos'
  delete '/photos/:id', to: 'blogs#destroy_photo', as: 'photo'
  put '/destination/select_top', to: 'blogs#select_top', as: 'select_top'
  post '/support', to: 'visitors#support', as: 'support'

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	
	before_filter :get_locations

	def home
		@main_blog = Blog.latest_blog
	end

	def solblog
		@main_blogs = Blog.main_blogs.paginate(page: params[:page], per_page: 2)
	end

	def mysol
		@mysol_blog = Blog.my_sol_blogs.first
	end

	def destination
		@location = Location.includes(:blogs).includes(:photos).find_by_name params[:name]
		@photo = @location.photo.picture.url
		@photos = @location.all_photos.limit 12
		@destination = @location.blogs.destination.first
		@eat_blogs = @location.blogs.eat
		@stay_blogs = @location.blogs.stay
		@play_blogs = @location.blogs.play
		@featured_blogs = @location.sub_blogs.featured
	end

	def travel
	end

	def support
		SupportMailer.notify(params[:support][:email], params[:support][:title], params[:support][:body]).deliver

		redirect_to travel_path, notice: 'Email is successfully sent.'
	end

end

app/views/visitors/destination.html.erb
<div>
    <div class="header">
        <%= link_to destination_path(name: params[:name]) do %>
            <div class='title'><%= params[:name] %></div>
            <%= image_tag @photo, id:"dest_blog_img", class: "blog_big_img", title: @photo %>
        <% end %>
    </div>
    <div class="submenu">
        <div style="width:15%" class="pull-left"><hr/></div>
        <%= link_to 'eat', 'javascript:void(0)', data: {target: '#eat_blog_div'}, class: "submenu_title pull-left" %>
        <div style="width:14%;" class="pull-left"><hr/></div>
        <%= link_to 'play', 'javascript:void(0)', data: {target: '#play_blog_div'}, class: 'submenu_title pull-left' %>
        <div style="width:14%;" class="pull-left"><hr/></div>
        <%= link_to 'stay', 'javascript:void(0)', data: {target: '#stay_blog_div'}, class: 'submenu_title pull-left' %>
        <div style="width:15%;" class="pull-left"><hr/></div>
    </div>

    <div id="location_blog_div">
        <div class="sol_blog_section">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>STORY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <div>
            <% unless @destination.nil? %>
                <div class="blog_title title_field">
                    <%= @destination.title %>
                </div>
                <div>
                    <%= image_tag @destination.picture.url, class: "blog_mid_img" %>
                </div>
                <div class="blog_content">
                    <%= raw @destination.body %>
                </div>
            <% end %>
        </div>
        <div>
            <div class="blog_line_bar">
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div class="pull-left" style="width:20%"><h2>TOP <%= @featured_blogs.count   %></h2></div>
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>

            <div class="row">
                <div class="col-sm-8 col-xs-12">
                    <% @featured_blogs.each_with_index do |blog, index| %>
                        <%= image_tag blog.picture.url, id: "featured-img-#{index}", class: "#{index == 0 ? 'show' : 'hidden'} featured_image" %>
                    <% end %>
                </div>
                <div class="col-sm-4 col-xs-12">
                    <div class="row">
                        <div class="col-sm-12 col-xs-12" data-current="0" data-total="<%= @featured_blogs.count %>" id="control-bar">
                            <div class="col-sm-4 col-xs-4 pull-left">
                                <%= image_tag '/assets/themes/light/panel-prev-big.png', class: 'blog_nav_img', id: "featured-left"%>
                            </div>
                            <div id="featured-status" class="col-sm-4 col-xs-4 pull-left"></div>
                            <div class="col-sm-4 col-xs-4 pull-left">
                                <%= image_tag '/assets/themes/light/panel-next-big.png', class: 'blog_nav_img', id: "featured-right"%>
                            </div>
                        </div>
                    </div>
                    <% @featured_blogs.each_with_index do |blog, index| %>
                        <span id="featured-blog-<%=index %>", class="<%= index == 0 ? 'show' : 'hidden'%> featured_blog" >
                            <%= raw blog.body%>
                        </span>
                    <% end %>
                </div>
            </div>
        </div>
        <div>
            <div class="blog_line_bar">
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div class="pull-left" style="width:20%"><h2>PHOTOS</h2></div>
                <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>

            <div id="pinterest">
                <div id="pinterest_photo">
                    <% @photos.each do |photo| %>
                        <div>
                            <%= link_to photo.picture.url do %>
                                <%= image_tag photo.picture.url(:thumb), class: "img-thumbnail", style: "width:150px" %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>


    <div id="eat_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>EAT</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @eat_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
                                
            </div>
            <hr class="clearfix large_margin" />
        <% end %>
    </div>

    <div id="play_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>PLAY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @play_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
            </div>
            <hr class="large_margin" />
        <% end %>
    </div>

    <div id="stay_blog_div">
        <div class="blog_line_bar">
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div class="pull-left" style="width:20%"><h2>STAY</h2></div>
            <div class="pull-left hr_div" style="width:40%"><hr/><hr/></div>
            <div style="clear: both;"></div>
        </div>
        <% @stay_blogs.each do |blog| %>
            <div class="row">
                <div class="col-sm-8">
                    <%= link_to url_with_protocol(blog.link_url) do %>
                        <%= image_tag blog.picture.url %>
                    <% end %>
                </div>
                <div class="col-sm-4">
                    <h4><%= blog.title %></h4>
                    <span class="featured_blog_content">
                        <%= raw blog.body %>
                    </span>
                </div>
            </div>
            <hr class="large_margin" />
        <% end %>
    </div>
    
</div>

app/views/visitors/home.html.erb
<div class="sol_blog">
    <div class="col-sm-12">
        <div id="gallery_large" class="image_gallery">
            <ul id="myGallery">
                <% @locations.each do |l| %>
                    <li><%= image_tag l.photo.picture.url, title: l.name, id: "#{l.name}", data: {target: "#{destination_url(name: l.name)}"} %></li>
                <% end %>
            </ul>
        </div>
        <div id="gallery_small" class="image_gallery">
            <ul class="bxslider">
                <% @locations.each do |l| %>
                    <li>
                        <%= image_tag l.photo.picture.url, title: l.name, data: {target: "#{destination_url(name: l.name)}"} %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="sol_blog_section">
            <div>
                <div class="pull-left hr_div" style="width:35%;"><hr/><hr/></div>
                <div class="pull-left" style="width:30%;"><h2>SOL BLOG</h2></div>
                <div class="pull-left hr_div" style="width:35%;"><hr/><hr/></div>
                <div style="clear: both;"></div>
            </div>
            <br />
            <div class="sol_blog_main">
                <% unless @main_blog.nil? %>
                    <div class="blog_title title_field">
                        <%= link_to solblog_path do %>
                            <%= @main_blog.title %>
                        <% end %>
                    </div>
                    <div>
                        <%= image_tag @main_blog.picture.url, class: "blog_mid_img" %>
                    </div>
                    <div class="blog_content">
                        <%= raw @main_blog.body %>
                    </div>
                <% end %>
            </div>
        </div>
        <div>
            <div class="sol_blog_section">
                <div class="pull-left hr_div" style="width:32%;"><hr/><hr/></div>
                <div class="pull-left" style="width:36%;"><h2>INSTAGRAM</h2></div>
                <div class="pull-left hr_div" style="width:32%;"><hr/><hr/></div>
                <div class="pull-left" style="clear: both;"></div>
            </div>
            <br />
            <div id="wrapper">
                <div id="instafeed"></div>
            </div>
        </div>    
        </div>
    </div>
</div>
<br />
<br />

app/views/visitors/index.html.erb
<h3>Welcome</h3>

app/views/visitors/mysol.html.erb
<div class="col-sm-12">
    <% unless @mysol_blog.nil? %>
        <div class="about_image">
            <%= image_tag @mysol_blog.picture.url, class: "blog_big_img" %>
        </div>
        <div class="quote text-center">
            <div class="quote_font">&ldquo;</div>
            <div class="quote_text">
                &nbsp;&nbsp;
                <%= @mysol_blog.title %>
                &nbsp;&nbsp;</div>
            <div class="quote_font">&rdquo;</div>
        </div>
        <hr />
        <div class="about_content">
            <%= raw @mysol_blog.body %>
        </div>
    <% end %>
    <hr />
</div>

app/views/visitors/solblog.html.erb
<div class="main" style="text-align:center">
    <h2>SOL BLOG</h2>
        <% @main_blogs.each do |blog| %>
            <div class="blog_section">
                <div class="blog_title">
                    <div class="title_field"><%= blog.title %></div>
                    <div class="date_field"><%=  blog.created_at.strftime "%D" %></div>
                </div>
                <div style="clear:both"></div>
                <div>
                    <%= image_tag blog.picture.url, class: "" %>
                </div>
                <div class="blog_content"><%= raw blog.body %></div>
            </div>
            <hr />
        <% end %>
    <%= will_paginate @main_blogs, renderer: BootstrapPagination::Rails %>
</div>

app/views/visitors/travel.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= form_for :support, url: support_path, method: :post do |f| %>
		  <div class="form-group">
		    <%= f.label :email %>
		    <%= f.text_field :email, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		    <%= f.label :title %>
		    <%= f.text_field :title, class: 'form-control' %>
		  </div>
		  <div class="form-group">
		    <%= f.label :body %>
		    <%= f.text_area :body, rows: 5, class: 'form-control' %>
		  </div>
		  <button type="submit" class="btn btn-default">Submit</button>
		<% end %>
	</div>
	<br />
	<br />
</div>