config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'

  devise_for :users, controllers: {sessions: 'sessions'}

  get '/home', to: 'visitors#home', as: 'home'
  get '/mysol', to: 'visitors#mysol', as: 'mysol'
  get '/destination', to: 'visitors#destination', as: 'destination'
  get '/solblog', to: 'visitors#solblog', as: 'solblog'
  get '/travel', to: 'visitors#travel', as: 'travel'

  resources :blogs
  resources :locations

  post '/photos/create', to: 'blogs#create_photo', as: 'photos'
  delete '/photos/:id', to: 'blogs#destroy_photo', as: 'photo'
  put '/destination/select_top', to: 'blogs#select_top', as: 'select_top'
  post '/support', to: 'visitors#support', as: 'support'

end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :photos, dependent: :destroy
	has_many :blogs, dependent: :destroy

	validates_presence_of :name
	validates_uniqueness_of :name

	def sub_blogs
		self.blogs.where(category: false)
	end

	def photo
		photos.where(landing: true).first
	end

	def all_photos
		photos.where(landing: false)
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!

  before_filter :get_locations

  def index
    @locations = Location.all
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new name: location_params[:name]
    if @location.save
      @photo = Photo.new picture: location_params[:photo], title: @location.name
      @photo.location_id = @location.id
      @photo.save

      redirect_to locations_path, notice: "Location is successfully created."
    else
      redirect_to new_location_path, alert: "Failed to create location."
    end
  end

  def update
    @location = Location.find(params[:id])

    if @location.update_attributes name: location_params[:name]
      @photo = @location.photo
      if @photo.nil?
        @photo = Photo.new
        @photo.location_id = @location.id
      end
      @photo.update_attributes picture: location_params[:photo], title: @location.name

      redirect_to locations_path, notice: "Location is successfully updated."
    else
      redirect_to new_location_path, alert: "Failed to update location."
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_path, notice: 'Location is successfully destroyed.'
  end

  def show
    @location = Location.find(params[:id])
  end

  private

  def location_params
    params.require(:location).permit(:name, :photo)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
.col-sm-8.col-sm-offset-2
	= render 'layouts/messages'
	%h2 Add New Location
	%br
	= form_for @location, class: 'form-horizontal' do |f|
		= f.label :name
		= f.text_field :name, class: 'form-control'

		%br

		= f.label :photo
		= f.file_field :photo

		%br

		= f.submit class: 'btn btn-default'
		= link_to 'Cancel', locations_path, class: 'btn btn-default'

app/views/locations/edit.html.haml
= render 'form'

app/views/locations/index.html.haml
.main
	.row
		.col-sm-12
			= render 'layouts/messages'
			
			= link_to 'Add New Location', new_location_path, class: 'btn btn-success pull-right'
			%table.table{:align=> 'center'}
				%thead
					%td Name
					%td Photo
					%td Created At
				%tbody
					- if @locations.length > 0
						- @locations.each do |l|
							%tr
								%td= l.name
								%td
									- unless l.photo.nil? || l.photo.picture.nil?
										= image_tag l.photo.picture.url(:thumb)
								%td= l.created_at.strftime "%D"
								%td
									= link_to 'Edit', edit_location_path(l), class: "btn btn-primary btn-xs"
									= link_to 'Delete', location_path(l), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary btn-xs"
					- else
						%tr
							%td{colspan: 5}
								%h3
									There's no locations yet. Add 
									= link_to 'new location', new_location_path
									here.

app/views/locations/new.html.haml
= render 'form'

app/views/locations/show.html.haml
%h1 Locations#show
%p Find me in app/views/locations/show.html.haml