config/routes.rb
Rails.application.routes.draw do
  
  root to: 'visitors#home'

  devise_for :users, controllers: {sessions: 'sessions'}

  get '/home', to: 'visitors#home', as: 'home'
  get '/mysol', to: 'visitors#mysol', as: 'mysol'
  get '/destination', to: 'visitors#destination', as: 'destination'
  get '/solblog', to: 'visitors#solblog', as: 'solblog'
  get '/travel', to: 'visitors#travel', as: 'travel'

  resources :blogs
  resources :locations

  post '/photos/create', to: 'blogs#create_photo', as: 'photos'
  delete '/photos/:id', to: 'blogs#destroy_photo', as: 'photo'
  put '/destination/select_top', to: 'blogs#select_top', as: 'select_top'
  post '/support', to: 'visitors#support', as: 'support'

end

app/views/layouts/_header.html.erb
<div class="container">
<div>
    <div class="banner">
        <% if user_signed_in? %>
            <%= link_to locations_path do %>
                <%= image_tag 'logo.jpg', :class=>'banner_img' %>
            <% end %>
        <% else %>
            <%= link_to root_path do %>
                <%= image_tag 'logo.jpg', :class=>'banner_img' %>
            <% end %>
        <% end %>
    </div>
    <div class="menubar">
        <hr/><hr/>
        <div id="menu_small" class="menu_container">
            <ul class="nav nav-pills">
                <li>
                    <% if user_signed_in? %>
                        <%= link_to "SOL BLOG", blogs_path(type: Blog::BLOG_MAIN) %>
                    <% else %>
                        <%= link_to "SOL BLOG", solblog_path, class: "#{header_selected 'solblog'}" %>
                    <% end %>
                </li>
                <li class="menu_dot">&bull;</li>
                <li class="dropdown">
                    <a class="dropdown-toggle <%= header_selected 'destination' %>" data-toggle="dropdown" href="#"  >
                        DESTINATION<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <% @locations.each do |l| %>
                            <li>
                            <% if user_signed_in? %>
                                <%= link_to l.name, blogs_path(name: l.name) %>
                            <% else %>
                                <%= link_to l.name, destination_path(name: l.name) %>
                            <% end %>
                            </li>
                        <% end %>
                    </ul>
                </li>
                <li class="menu_dot">&bull;</li>
                <li>
                    <% if user_signed_in? %>
                        <%= link_to "MY SOL", blogs_path(type: Blog::BLOG_MYSOL) %>
                    <% else %>
                        <%= link_to "MY SOL", mysol_path, class: "short_title #{header_selected 'mysol'}" %>
                    <% end %>
                </li>
                <li class="menu_dot">&bull;</li>
                <li>
                    <%= link_to "TRAVEL CONSULTANT", travel_path, class: "long_title #{header_selected 'travel'}" %>
                </li>
            </ul>
        </div>
        <hr/>
        <hr/>
    </div>

    <div class="web_links">
        <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% else %>
            <a href="http://instagram.com/mysimplesol" class="share_icon" target="_blank" title="Share on Instagram">
                <img src="/assets/share_instagram.jpg">
            </a>
            <a href="http://www.pinterest.com/thesimplesol" class="share_icon" target="_blank" title="Share on Pinterst">
                <img src="/assets/share_pinterst.jpg">
            </a>
            <a href="http://twitter.com/thesimplesol" class="share_icon" target="_blank" title="Share on Twitter">
                <img src="/assets/share_twitter.jpg">
            </a>
            <a href="http://www.facebook.com/thesimplesol" class="share_icon" target="_blank" title="Share on Facebook">
                <img src="/assets/share_facebook.jpg">
            </a>
            <a href="#" class="share_icon" target="_blank" title="Share on Google">
                <img src="/assets/share_google.jpg">
            </a>
            <a href="#" class="share_icon" target="_blank" title="Share on SoundCloud">
                <img src="/assets/share_soundcloud.jpg">
            </a>
        <% end%>
    </div>

</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
    	<button class="close" aria-hidden="true" data-dismiss="alert" type="button">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Solblog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Solblog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div role="main" class="container">
      <%= yield %>
    </div>
  </body>
</html>